[build]
  command = "pnpm install && pnpm build && bash copy-json.sh"
  publish = "out"
  
[[redirects]]
  from = "/radio"
  to = "/radio.html"
  status = 200

[[redirects]]
  from = "/media-library.json"
  to = "/media-library.json"
  status = 200
  force = false
